ALTER TABLE `locales_creature`
ADD COLUMN `nameAlt_loc1`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `name_loc11`,
ADD COLUMN `nameAlt_loc2`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `nameAlt_loc1`,
ADD COLUMN `nameAlt_loc3`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `nameAlt_loc2`,
ADD COLUMN `nameAlt_loc4`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `nameAlt_loc3`,
ADD COLUMN `nameAlt_loc5`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `nameAlt_loc4`,
ADD COLUMN `nameAlt_loc6`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `nameAlt_loc5`,
ADD COLUMN `nameAlt_loc7`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `nameAlt_loc6`,
ADD COLUMN `nameAlt_loc8`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `nameAlt_loc7`,
ADD COLUMN `nameAlt_loc9`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `nameAlt_loc8`,
ADD COLUMN `nameAlt_loc10`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `nameAlt_loc9`,
ADD COLUMN `nameAlt_loc11`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `nameAlt_loc10`,
ADD COLUMN `subnameAlt_loc1`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `subname_loc11`,
ADD COLUMN `subnameAlt_loc2`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `subnameAlt_loc1`,
ADD COLUMN `subnameAlt_loc3`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `subnameAlt_loc2`,
ADD COLUMN `subnameAlt_loc4`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `subnameAlt_loc3`,
ADD COLUMN `subnameAlt_loc5`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `subnameAlt_loc4`,
ADD COLUMN `subnameAlt_loc6`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `subnameAlt_loc5`,
ADD COLUMN `subnameAlt_loc7`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `subnameAlt_loc6`,
ADD COLUMN `subnameAlt_loc8`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `subnameAlt_loc7`,
ADD COLUMN `subnameAlt_loc9`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `subnameAlt_loc8`,
ADD COLUMN `subnameAlt_loc10`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `subnameAlt_loc9`,
ADD COLUMN `subnameAlt_loc11`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `subnameAlt_loc10`;

